package com.example.stingymen;

import androidx.appcompat.app.AlertDialog;
import androidx.appcompat.app.AppCompatActivity;

import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.drawable.Drawable;
import android.graphics.pdf.PdfDocument;
import android.media.Image;
import android.os.Bundle;
import android.provider.DocumentsContract;
import android.view.Gravity;
import android.view.LayoutInflater;
import android.view.View;
import android.view.Window;
import android.view.WindowManager;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;
import android.widget.Toast;

import com.bumptech.glide.Glide;
import com.gkemon.XMLtoPDF.PdfGenerator;
import com.gkemon.XMLtoPDF.PdfGeneratorListener;
import com.gkemon.XMLtoPDF.model.FailureResponse;
import com.gkemon.XMLtoPDF.model.SuccessResponse;

import org.w3c.dom.Document;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.MalformedURLException;

import static com.example.stingymen.MainActivity.editTextBranch;
import static com.example.stingymen.MainActivity.editTextName;
import static com.example.stingymen.MainActivity.editTextPosition;
import static com.example.stingymen.MainActivity.profileImage;
import static com.example.stingymen.MainActivity.selectedImage;

public class PrintID extends AppCompatActivity {
    Button printID;
    TextView textView_name, textView_position, textView_branch, textView_idNo;
    ImageView imageView_profileImage;
    private static String FILE = "mnt/sdcard/invoice.pdf";
    Bitmap screen;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_print_i_d);
         showIdDialog();
        printID = findViewById(R.id.print_ID);

           printID.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                System.out.println("clicked");
                PdfGenerator.getBuilder()
                        .setContext(getApplicationContext())
                        .fromLayoutXMLSource()
                        .fromLayoutXML(R.layout.activity_print_i_d,R.layout.activity_print_i_d)
                        /* "fromLayoutXML()" takes array of layout resources.
                         * You can also invoke "fromLayoutXMLList()" method here which takes list of layout resources instead of array. */
                        .setDefaultPageSize(PdfGenerator.PageSize.A4)
                        /* It takes default page size like A4,A5. You can also set custom page size in pixel
                         * by calling ".setCustomPageSize(int widthInPX, int heightInPX)" here. */
                        .setFileName("Test-PDF")
                        /* It is file name */
                        .setFolderName("FolderA/FolderB/FolderC")
                        /* It is folder name. If you set the folder name like this pattern (FolderA/FolderB/FolderC), then
                         * FolderA creates first.Then FolderB inside FolderB and also FolderC inside the FolderB and finally
                         * the pdf file named "Test-PDF.pdf" will be store inside the FolderB. */
                        .openPDFafterGeneration(true)
                        /* It true then the generated pdf will be shown after generated. */
                        .build(new PdfGeneratorListener() {
                            @Override
                            public void onFailure(FailureResponse failureResponse) {
                                super.onFailure(failureResponse);
                                /* If pdf is not generated by an error then you will findout the reason behind it
                                 * from this FailureResponse. */
                            }

                            @Override
                            public void showLog(String log) {
                                super.showLog(log);
                                /*It shows logs of events inside the pdf generation process*/
                            }

                            @Override
                            public void onSuccess(SuccessResponse response) {
                                super.onSuccess(response);
                                /* If PDF is generated successfully then you will find SuccessResponse
                                 * which holds the PdfDocument,File and path (where generated pdf is stored)*/

                            }
                        });

            }
        });
    }

    private void showIdDialog(){
        final AlertDialog.Builder dialog=new AlertDialog.Builder(this,R.style.CustomAlertDialog);
        LayoutInflater inflater = LayoutInflater.from(this);
        View id_layout = inflater.inflate(R.layout.activity_i_d,null);
        textView_name=id_layout.findViewById(R.id.textView_name);
        textView_position=id_layout.findViewById(R.id.textView_position);
        textView_branch=id_layout.findViewById(R.id.textView_branch);
        textView_idNo=id_layout.findViewById(R.id.textView_idNo);
        imageView_profileImage=id_layout.findViewById(R.id.imageView_profileImage);
        dialog.setView(id_layout);
        textView_name.setText(editTextName.getText());
        textView_position.setText(editTextPosition.getText());
        textView_branch.setText(editTextBranch.getText());
        textView_idNo.setText("NG042"+ editTextName.getText().subSequence(4,5));
        Glide.with(id_layout.getContext())
             .load(selectedImage)
                .into(imageView_profileImage);
        dialog.setCancelable(false);
        //dialog.show();
        final AlertDialog Dial =dialog.create();
        Dial.requestWindowFeature(Window.FEATURE_NO_TITLE);
        WindowManager.LayoutParams wmlp = Dial.getWindow().getAttributes();
        wmlp.gravity = Gravity.BOTTOM| Gravity.CENTER_HORIZONTAL;
        wmlp.y = 500;
        Dial.show();
        Dial.getWindow().setLayout(1000,800);


      
        PdfGenerator.getBuilder()
                .setContext(getApplicationContext())
                .fromLayoutXMLSource()
                .fromLayoutXML(R.layout.activity_print_i_d)
                .setDefaultPageSize(PdfGenerator.PageSize.A4)
                .setFileName("Test-PDF")
                .build(new PdfGeneratorListener() {
                    @Override
                    public void onFailure(FailureResponse failureResponse) {
                        super.onFailure(failureResponse);
                    }

                    @Override
                    public void showLog(String log) {
                        super.showLog(log);
                    }

                    @Override
                    public void onSuccess(SuccessResponse response) {
                        super.onSuccess(response);
                    }
                });
    }
}